### PR TITLE
Add GFM syntax highlighting to README.md

### PR DESCRIPTION
**Pull request by Zearin**

### CODE REVIEW

**Comment by Zearin** [comment]
ping!

**Comment by Zearin** [comment]
ping

**Comment by Zearin** [comment]
@andreyvit ping

**Comment by Zearin** [comment]
10 years old?!

I surrender 🙇‍♂️

**Comment by andreyvit** [comment]
Lol. Has it really been 10 years since all of that? :)

**Comment by andreyvit** [comment]
I apologize, though, I didn't do a good job maintaining LiveReload at all.

**Pull request closed without merging**
